spring.application.name=Project
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/Project
spring.datasource.username=root
spring.datasource.password=Dharani

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
